#!/bin/bash
#PBS -N test_rocm
#PBS -l select=1:node_type=mi300a:ncpus=4
#PBS -l walltime=24:00:00
#PBS -o /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/test_rocm.log
#PBS -e /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/test_rocm.err

# Change to the direcotry that the job was submitted from
# conda activate /zhome/academic/HLRS/xmu/xmuyzsun/env/diffusionnag/ 
cd $WK0
echo $WK0
echo $(date) >> /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/test_rocm.log
echo $(date) >> /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/test_rocm.err
module load rocm/6.1.0
module load python
python3 --version
source /zhome/academic/HLRS/xmu/xmuyzsun/env/ofa-cifar/bin/activate
# nvidia-smi
# lscpu
# env_path="$HOME/env/diffusionnag/bin/activate"
# env_path="$HOME/env/graphdit_env/bin/activate"
# source $env_path
# conda activate $HOME/env/diffusionnag

###########################################################
start_time=$(date +%s)
python3 test_rocm.py
end_time=$(date +%s)
###########################################################

elapsed_time=$(( end_time - start_time ))
echo "time:  $elapsed_time s$"