

#!/bin/bash
#PBS -N train_mbv3_cifar_teacher
#PBS -l select=1:node_type=mi300a:ncpus=40
#PBS -l walltime=24:00:00
#PBS -o /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/train_ofa_224teacher32_net.log
#PBS -e /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/train_ofa_224teacher32_net.err

# Change to the direcotry that the job was submitted from
# conda activate /zhome/academic/HLRS/xmu/xmuyzsun/env/diffusionnag/
export CUDA_VISIBLE_DEVICES=0
cd $WK0/ofa-cifar/
echo $WK0
echo $(date) >> /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/train_ofa_224teacher32_net.log
echo $(date) >> /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/train_ofa_224teacher32_net.err
module use /opt/hlrs/testing/ai-frameworks/modulefiles
module load pytorch
source ~/.venv/ofa-cifar-hunter/bin/activate
# module load rocm/6.1.0
# module load python
# python3 --version
# source /zhome/academic/HLRS/xmu/xmuyzsun/env/ofa-cifar/bin/activate
# nvidia-smi
# lscpu
# env_path="$HOME/env/diffusionnag/bin/activate"
# env_path="$HOME/env/graphdit_env/bin/activate"
# source $env_path
# conda activate $HOME/env/diffusionnag

###########################################################
start_time=$(date +%s)
python train_ofa_net.py
end_time=$(date +%s)
###########################################################

elapsed_time=$(( end_time - start_time ))
echo "time:  $elapsed_time s$"