#!/bin/bash
#PBS -N evaluate_cifar10_part_8
#PBS -l select=2:node_type=mi300a:mpiprocs=4:ncpus=96
#PBS -l walltime=24:00:00
#PBS -o /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/eval_part_8.log
#PBS -e /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/eval_part_8.err

cd $WK0/ofa-cifar/test_mbv3/
echo $WK0
echo $(date) >> /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/eval_part_8.log
echo $(date) >> /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/eval_part_8.err

module use /opt/hlrs/testing/ai-frameworks/modulefiles
module load pytorch
source ~/.venv/ofa-cifar-hunter/bin/activate

export DEEPSPEED_HOSTFILE=deepspeed.hostfile
WORLD_SIZE=`cat $PBS_NODEFILE | wc -l`

sort $PBS_NODEFILE | awk -F'.' '{print $1}' | uniq | while read node; do
    echo "$node slots=4"
done > "$DEEPSPEED_HOSTFILE"
export HEAD_NODE_IP=$(head -n 1 $PBS_NODEFILE | awk -F'.' '{print $1}')
export MASTER_PORT=29500
export MASTER_ADDR=$HEAD_NODE_IP

if [ -f $PBS_NODEFILE ]; then
  > $DEEPSPEED_HOSTFILE
  sort $PBS_NODEFILE | uniq | while read host; do
    short_name=$(echo $host | cut -d '.' -f 1)
    echo "$short_name slots=4" >> $DEEPSPEED_HOSTFILE
  done
else
  echo "Error: PBS_NODEFILE not found!"
  exit 1
fi

GRAPH_DIR="${WK0}ofa-cifar/test_mbv3/graphs"
SCRIPT="evaluate_mbv3_cifar10.py"
# python test_final_graphs_cifar10.py

# Processing files: $GRAPH_DIR/cifar10_graph_024.json $GRAPH_DIR/cifar10_graph_025.json $GRAPH_DIR/cifar10_graph_026.json
for graph_file in $GRAPH_DIR/cifar10_graph_024.json $GRAPH_DIR/cifar10_graph_025.json $GRAPH_DIR/cifar10_graph_026.json; do
    echo "📂 Evaluating $graph_file"
    mpirun -np $WORLD_SIZE \
            --ppn 4 \
            --genvall \
            --cpu-bind list:0-23:24-47:48-71:72-95 \
            --gpu-bind none \
            --no-transfer \
            -genv WORLD_SIZE=$WORLD_SIZE \
            -genv LOCAL_SIZE=4 \
            python -u /opt/hlrs/testing/ai-frameworks/DeepSpeed/deepspeed/launcher/launcher_helper.py \
            --launcher mpich \
            $SCRIPT --input "$graph_file"
done

# Final Summary
# echo -e "\n📊 Final Summary:"
# python $SCRIPT --input $GRAPH_DIR/cifar10_graph_024.json $GRAPH_DIR/cifar10_graph_025.json $GRAPH_DIR/cifar10_graph_026.json
