#!/bin/bash
#PBS -N evaluate_cifar10_part_0
#PBS -l select=2:node_type=mi300a:mpiprocs=4:ncpus=96
#PBS -l walltime=24:00:00
#PBS -o /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/eval_32part_0.log
#PBS -e /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/eval_32part_0.err

cd $WK0/ofa-cifar/test_mbv3/
echo $WK0
echo $(date) >> /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/eval_32part_0.log
echo $(date) >> /lustre/hpe/ws12/ws12.a/ws/xmuyzsun-WK0/outputs/eval_32part_0.err

module use /opt/hlrs/testing/ai-frameworks/modulefiles
module load pytorch
source ~/.venv/ofa-cifar-hunter/bin/activate

export DEEPSPEED_HOSTFILE=deepspeed.hostfile
WORLD_SIZE=`cat $PBS_NODEFILE | wc -l`

sort $PBS_NODEFILE | awk -F'.' '{print $1}' | uniq | while read node; do
    echo "$node slots=4"
done > "$DEEPSPEED_HOSTFILE"
export HEAD_NODE_IP=$(head -n 1 $PBS_NODEFILE | awk -F'.' '{print $1}')
export MASTER_PORT=29500
export MASTER_ADDR=$HEAD_NODE_IP

if [ -f $PBS_NODEFILE ]; then
  > $DEEPSPEED_HOSTFILE
  sort $PBS_NODEFILE | uniq | while read host; do
    short_name=$(echo $host | cut -d '.' -f 1)
    echo "$short_name slots=4" >> $DEEPSPEED_HOSTFILE
  done
else
  echo "Error: PBS_NODEFILE not found!"
  exit 1
fi

GRAPH_DIR="${WK0}ofa-cifar/test_mbv3/graphs"
SCRIPT="evaluate_mbv3_cifar10.py"
python test_final_graphs_cifar10.py